Repository plus1250-project/joba-react-frontend, pull requests merged in 2022-07, with the labels that each got.

#15 Feature/keyword chart
  public/index.html
  src/App.js
  src/components/Commons/Modal.js
  src/components/Commons/Modal.module.scss
  src/components/Layout/Layout.js
  src/components/Sidebar/LinksGroup/LinksGroup.js
  src/index.js
  src/pages/dashboard/Dashboard.js
  src/pages/dashboard/components/ArticlesList.js
  src/pages/dashboard/components/CorpIndustry.js
  src/pages/dashboard/components/CorpList.js
  src/pages/dashboard/components/KeywordBlock.js
  src/pages/dashboard/components/TrendChart.js
  src/pages/tables/Tables.module.scss
  src/pages/tables/components/ArticleContainer/ArticleContainer.js
  src/pages/tables/components/ArticleContainer/ArticleContainer.module.scss
  src/pages/tables/components/CorpContainer/CorpContainer.js
  src/pages/uielements/charts/components/ApexLineColumnChart.js
  src/reducers/navigation.js
Labels: feature

#17 [Feat]Bubble Chart
  package-lock.json
  package.json
  src/pages/dashboard/components/Bubble.js
  src/pages/dashboard/components/KeywordBubbleChart.js
  src/pages/dashboard/components/StatefullBubble.js
  src/pages/tables/Tables.module.scss
  yarn.lock
Labels: feature

#19 [Refactor] increase keyword
  src/pages/dashboard/components/KeywordBlock.js
Labels: refactor

#20 [Refactor] monthly rank list
  src/pages/dashboard/components/MonthlyRankList.js
Labels: refactor

#21 [Refactor] compare keyword
  src/pages/dashboard/Dashboard.js
  src/pages/dashboard/components/CompareKeywordList.js
Labels: refactor

#27 [Feat] add Redux & [Refactor] indus corp list
  src/actions/industry.js
  src/components/Commons/Modal.module.scss
  src/pages/dashboard/Dashboard.js
  src/pages/dashboard/components/CorpIndustry.js
  src/pages/dashboard/components/CorpList.js
  src/pages/tables/Tables.module.scss
  src/pages/tables/components/CorpContainer/CorpContainer.js
  src/reducers/index.js
  src/reducers/industry.js
  src/reducers/navigation.js
Labels: refactor, feature

#31 [Feat] trend chart
  src/actions/bubble.js
  src/components/Sidebar/LinksGroup/LinksGroup.js
  src/pages/dashboard/Dashboard.js
  src/pages/dashboard/components/Bubble.js
  src/pages/dashboard/components/CompareKeywordList.js
  src/pages/dashboard/components/MonthlyRankList.js
  src/pages/dashboard/components/TrendChart.js
  src/pages/tables/components/ArticleContainer/ArticleContainer.module.scss
  src/pages/uielements/charts/components/ApexLineColumnChart.js
  src/reducers/bubble.js
  src/reducers/index.js
Labels: feature

#34 [Fix] side bar
  src/components/Breadbrumbs/Breadcrumbs.js
  src/components/Layout/Layout.js
  src/components/Sidebar/Sidebar.js
  src/pages/dashboard/components/CorpIndustry.js
Labels: layout
